-- 코드를 입력하세요
SELECT C.YEAR, C.MONTH, COUNT(DISTINCT C.USER_ID) as PURCHASED_USERS, ROUND(COUNT(DISTINCT C.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED)=2021),1) as PUCHASED_RATIO
FROM (
SELECT A.USER_ID as USER_ID, YEAR(B.SALES_DATE) as YEAR, MONTH(B.SALES_DATE) as MONTH
FROM (
SELECT USER_ID
FROM USER_INFO
WHERE YEAR(JOINED)=2021) A join ONLINE_SALE B on A.USER_ID=B.USER_ID) C
GROUP BY MONTH