SELECT year(a.DIFFERENTIATION_DATE) as YEAR, b.SIZE-a.SIZE_OF_COLONY as YEAR_DEV, a.ID
FROM ECOLI_DATA a JOIN (
SELECT year(DIFFERENTIATION_DATE) as YEAR, max(SIZE_OF_COLONY) as SIZE
    FROM ECOLI_DATA
    GROUP BY year(DIFFERENTIATION_DATE)
) b ON year(a.DIFFERENTIATION_DATE)=b.YEAR
ORDER BY YEAR, YEAR_DEV