SELECT I.ID as ID, N.FISH_NAME as FISH_NAME, C.LENGTH as LENGTH
FROM FISH_INFO I JOIN FISH_NAME_INFO N ON I.FISH_TYPE=N.FISH_TYPE
JOIN (
SELECT FISH_TYPE, max(LENGTH) as LENGTH
FROM FISH_INFO
GROUP BY FISH_TYPE
) C ON C.FISH_TYPE=I.FISH_TYPE and C.LENGTH=I.LENGTH
ORDER BY I.ID