SELECT CONCAT('/home/grep/src/',F.BOARD_ID,'/',F.FILE_ID,F.FILE_NAME,F.FILE_EXT) as FILE_PATH
FROM USED_GOODS_FILE F JOIN (
SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
) V
ON V.BOARD_ID=F.BOARD_ID
ORDER BY FILE_PATH DESC